### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by Bin199** [voidism/DiffCSE#1]
Hi! I reproduce result of roberta-base on my device and all parameters are same as those in your paper. But I get the following error:
![a](https://user-images.githubusercontent.com/51829876/165491891-da4b3f0c-670c-4adf-aae0-c4b4b5a1970d.png)
![b](https://user-images.githubusercontent.com/51829876/165492019-6f756854-4604-42e5-8cd7-7147729457ec.png)

**Comment by voidism** [comment]
Hi!,

Which generator model are you using? For RoBERTa you should use `--generator_name distilroberta-base`. 
The default generator is DistilBERT so its index numbers will exceed RoBERTa's index number range.
