### ISSUE TITLE
Question about scalability wrt. input length

### ISSUE THREAD

**Issue by perceptiveshawty** [voidism/DiffCSE#12]
Howdy,

I was wondering if any experiments were done with the DiffCSE framework for long inputs (300-500 tokens), or ie. are there any conditions on the training data necessary for convergence?

PS - congrats on the paper, it was a really fun read :)

**Comment by voidism** [comment]
Thanks for the question. I haven't done any experiments using long sequences. But this paper did try using DiffCSE for passage retrieval https://arxiv.org/abs/2205.12035
It seems that DiffCSE still works with passages. And the method proposed in their paper (RetroMAE) seems more effective.

**Comment by perceptiveshawty** [comment]
Will check it out, thanks
