### ISSUE TITLE
第六章 Retrieval Task 的原始碼是否有放在 Github 呢?

### ISSUE THREAD

**Issue by Rachel-Yeah-Lee** [voidism/DiffCSE#16]
您好~ 謝謝您分享模型的原始碼！
我正在嘗試複製論文中的實驗，想請問您是否有將論文中 Table 9: Retrieved top-3 examples by SimCSE and DiffCSE from STS-B test set. 的實驗放上 github 呢? 如果有的話可以指引我原始碼的位置嗎? 謝謝您~

**Comment by voidism** [comment]
您好～抱歉今天才看到這個issue
retrieval的code沒有放上去，但基本上就是算完cosine similarity之後做np.argsort就可以計算了，可以參考 https://github.com/princeton-nlp/SimCSE#getting-started 來算similarity。謝謝～

**Comment by Rachel-Yeah-Lee** [comment]
了解了~ 感謝您的回覆😊
